import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // SideNote house rules. These come after the Next presets so they win.
  {
    linterOptions: {
      // A stale `eslint-disable` is a lie about the code. Fail on it.
      reportUnusedDisableDirectives: "error",
    },
    rules: {
      // CLAUDE.md non-negotiable #1: `any` is a bug, not a warning.
      "@typescript-eslint/no-explicit-any": "error",
      // `any` also arrives disguised: a bare `{}`, `Function`, or `Object`
      // annotation is an unsound type in the same family.
      "@typescript-eslint/no-unsafe-function-type": "error",
      "@typescript-eslint/no-wrapper-object-types": "error",
      // Unused code is caught, not tolerated, but `_`-prefixed args are
      // a deliberate signal and stay legal.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `wrangler types`, alongside next-env.d.ts above and for the
    // same reason. It ships eslint-disable directives aimed at rule versions we
    // do not necessarily have, and `reportUnusedDisableDirectives` then fails
    // the build over two lines in a 10,000-line file nobody wrote. Editing it
    // is pointless — the next `npm run cf-typegen` puts them back.
    "worker-configuration.d.ts",
    // Generated by `opennextjs-cloudflare build`.
    ".open-next/**",
  ]),
]);

export default eslintConfig;
