import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // SideNote house rules. These come after the Next presets so they win.
  {
    linterOptions: {
      // A stale `eslint-disable` is a lie about the code. Fail on it.
      reportUnusedDisableDirectives: "error",
    },
    rules: {
      // CLAUDE.md non-negotiable #1: `any` is a bug, not a warning.
      "@typescript-eslint/no-explicit-any": "error",
      // `any` also arrives disguised: a bare `{}`, `Function`, or `Object`
      // annotation is an unsound type in the same family.
      "@typescript-eslint/no-unsafe-function-type": "error",
      "@typescript-eslint/no-wrapper-object-types": "error",
      // Unused code is caught, not tolerated, but `_`-prefixed args are
      // a deliberate signal and stay legal.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Generated by Cluster C's toolchain. Not ours to lint, and linting it
    // breaks the build for reasons that say nothing about our code:
    // `reportUnusedDisableDirectives` fires on the blanket `eslint-disable`
    // that both generators write at the top of their output.
    //
    // .open-next is the Worker bundle produced by `opennextjs-cloudflare
    // build`. .wrangler is workerd's local state directory, written by
    // `wrangler dev` — which means whether lint passed used to depend on
    // whether anyone had run the dev server. worker-configuration.d.ts is
    // written by `wrangler types` and is still TYPECHECKED — it is where the
    // binding types come from — it is only excluded from lint.
    ".open-next/**",
    ".wrangler/**",
    "worker-configuration.d.ts",
  ]),
]);

export default eslintConfig;
