/**
 * Seed vectors: precomputed, verified, and absent until somebody generates them.
 *
 * WHY THIS IS NOT SIMPLY COMMITTED
 *
 * `SEED_CHUNKS` is built by a synchronous top-level `SPECS.map(build)` in
 * documents.ts. An embedding call is async and networked, so seed vectors
 * cannot be produced at module load the way seed chunks are — they have to be
 * computed once, ahead of time, and read back.
 *
 * The artifact is generated by `npm run embed:seed`, which needs real
 * credentials. It is deliberately NOT generated from the stub server: the stub
 * hashes words into buckets, which is lexical matching in disguise, and an
 * artifact full of stub vectors labelled `@cf/baai/bge-base-en-v1.5` would be
 * a file claiming an inference that never happened. This project has already
 * had to unpick one of those — twelve fixtures marked `suggestedBy: "model"`
 * for a model that had never run — and the rule learned from it is that a
 * fixture never claims provenance it does not have.
 *
 * So: absent by default, and the dense half serves uploaded documents only
 * until the artifact exists. `loadSeedVectors` says which of those it is.
 */
import { z } from "zod";
import { ChunkId, DocumentId } from "@/lib/schemas";
import { EMBEDDING_DIMENSIONS, EMBEDDING_MODEL } from "@/lib/assess/ai";
import { SEED_CHUNKS, SEED_DOCUMENTS } from "./documents";
import type { VectorRecord } from "@/lib/retrieval/vectors";

/** Where `npm run embed:seed` writes, relative to the project root. */
export const SEED_VECTOR_PATH = "src/lib/fixtures/seed-vectors.json";

/**
 * The artifact's shape.
 *
 * `model` and `dimensions` are recorded and then CHECKED, not merely stored.
 * An artifact generated against a different model — the stub, a 384-dimension
 * bge-small, a future replacement — is refused rather than silently ranking
 * everything wrongly. `textHash` is what detects seed text drifting away from
 * the vectors that were computed for it.
 */
export const SeedVectorArtifact = z.object({
  model: z.string().min(1),
  dimensions: z.int().positive(),
  generatedAt: z.string().min(1),
  vectors: z
    .array(
      z.object({
        id: ChunkId,
        textHash: z.string().length(64),
        values: z.array(z.number()).length(EMBEDDING_DIMENSIONS),
      }),
    )
    .min(1),
});
export type SeedVectorArtifact = z.output<typeof SeedVectorArtifact>;

export type SeedVectorState =
  | { readonly status: "absent" }
  | { readonly status: "unusable"; readonly reason: string }
  | { readonly status: "loaded"; readonly records: readonly VectorRecord[] };

/** activeSubstance per document, for the metadata a vector carries. */
function substanceOf(documentId: string): string {
  return (
    SEED_DOCUMENTS.find((d) => d.id === documentId)?.activeSubstance ?? "unknown"
  );
}

/**
 * Join the artifact to the seed chunks.
 *
 * Metadata is derived from `SEED_CHUNKS` / `SEED_DOCUMENTS` rather than stored
 * in the artifact, so it structurally cannot drift from the fixtures. A vector
 * whose chunk no longer exists is dropped — the same rule `dense.ts` applies at
 * query time, for the same reason.
 */
export function joinToChunks(
  artifact: SeedVectorArtifact,
): readonly VectorRecord[] {
  const byId = new Map(SEED_CHUNKS.map((c) => [c.id as string, c]));
  const records: VectorRecord[] = [];

  for (const entry of artifact.vectors) {
    const chunk = byId.get(entry.id);
    if (chunk === undefined) continue;
    records.push({
      id: ChunkId.parse(entry.id),
      values: entry.values,
      metadata: {
        documentId: DocumentId.parse(chunk.documentId),
        sourceType: chunk.sourceType,
        activeSubstance: substanceOf(chunk.documentId),
      },
    });
  }

  return records;
}

/** Validate an already-parsed artifact against this build's model. */
export function checkArtifact(raw: unknown): SeedVectorState {
  const parsed = SeedVectorArtifact.safeParse(raw);
  if (!parsed.success) {
    return {
      status: "unusable",
      reason: `seed-vectors.json did not match the expected shape: ${z
        .prettifyError(parsed.error)
        .replace(/\s+/g, " ")
        .slice(0, 160)}`,
    };
  }

  if (parsed.data.model !== EMBEDDING_MODEL) {
    return {
      status: "unusable",
      reason: `seed-vectors.json was generated with ${parsed.data.model}, but this build embeds with ${EMBEDDING_MODEL} — regenerate it with npm run embed:seed`,
    };
  }

  if (parsed.data.dimensions !== EMBEDDING_DIMENSIONS) {
    return {
      status: "unusable",
      reason: `seed-vectors.json holds ${parsed.data.dimensions}-dimension vectors, but this build expects ${EMBEDDING_DIMENSIONS}`,
    };
  }

  return { status: "loaded", records: joinToChunks(parsed.data) };
}

let cached: SeedVectorState | null = null;

/**
 * Read the artifact if it is there.
 *
 * Absent is a normal state, not an error: it means nobody has run
 * `npm run embed:seed` yet, and the dense half serves uploaded documents only.
 * Read through `node:fs` rather than imported, so the module resolves on
 * Workers and in a browser bundle where the file may not exist at all.
 */
export async function loadSeedVectors(): Promise<SeedVectorState> {
  if (cached !== null) return cached;

  try {
    const { readFile } = await import("node:fs/promises");
    const raw = await readFile(SEED_VECTOR_PATH, "utf8");
    cached = checkArtifact(JSON.parse(raw));
  } catch {
    cached = { status: "absent" };
  }

  return cached;
}

/** Test seam: forget what was read, so a test can write an artifact and reload. */
export function forgetSeedVectors(): void {
  cached = null;
}

/**
 * The seed vectors, or none.
 *
 * A getter rather than a const because the artifact is read from disk and may
 * not exist; callers that want to explain its absence use `loadSeedVectors`.
 */
export async function seedVectorRecords(): Promise<readonly VectorRecord[]> {
  const state = await loadSeedVectors();
  return state.status === "loaded" ? state.records : [];
}
