import "server-only";
import { audit } from "@/lib/audit";
import { getCloudflareEnv } from "@/lib/platform/env";
import {
  StoredCaseClaim,
  claimExpiryFrom,
  claimIsLive,
  type CaseClaim,
  type ClaimOutcome,
} from "@/lib/case/claim";
import { SEEDED_CASE_IDS, seededHolder } from "@/lib/case/seeded-claims";
import { dbFrom, schema } from "@/lib/db/client";
import type { ReviewerRuling } from "@/lib/schemas/assessment";
import type { IsoDate, IsoDateTime } from "@/lib/schemas/primitives";
import type { CoordinatorState, RuleOutcome } from "./case-coordinator";

/**
 * The app's view of case coordination.
 *
 * Every call site talks to this interface, and never to a Durable Object stub
 * directly. Two reasons, and the second is the one that matters:
 *
 * 1. `next dev` has no Durable Object binding, and the reviewer screens still
 *    have to work.
 * 2. A Durable Object stub is a network call dressed as a method call. Letting
 *    page components hold one would spread `idFromName` and RPC round trips
 *    through the UI layer, and the day the arbitration moves — to a facet, to
 *    a different key, to something that is not a DO at all — every one of them
 *    would need finding.
 */

export interface CaseCoordination {
  state(caseId: string): Promise<CoordinatorState>;
  /**
   * Who holds each case right now.
   *
   * The queue's question, and the one thing `idFromName(caseId)` cannot
   * answer: sixteen cases are sixteen objects, and an object addressed by one
   * case id knows nothing about the other fifteen. Behind the real
   * implementation this is one D1 query against a table those objects write
   * themselves; behind the stand-in it is a Map.
   *
   * Returns exactly what `buildRows` takes, so the queue, the rail and this
   * cannot drift into three different ideas of what a claim is.
   */
  held(): Promise<ReadonlyMap<string, CaseClaim>>;
  /**
   * `idempotencyKey` is generated by the CLIENT, once per intent.
   *
   * Client-side rather than server-side because the point is to recognise a
   * REPEAT of one intent, and only the client knows that two requests are the
   * same press of the same button. A key minted on the server would be new
   * every time and would recognise nothing.
   */
  claim(
    caseId: string,
    reviewerId: string,
    displayName: string,
    idempotencyKey?: string | null,
  ): Promise<ClaimOutcome>;
  release(
    caseId: string,
    reviewerId: string,
    idempotencyKey?: string | null,
  ): Promise<CoordinatorState>;
  rule(
    caseId: string,
    ruling: ReviewerRuling,
    idempotencyKey?: string | null,
  ): Promise<RuleOutcome>;
  /** Idempotent. `null` stands the clock down. */
  armClock(
    caseId: string,
    reference: string,
    dueOn: IsoDate | null,
  ): Promise<void>;
  /** Next public reference for `year`. `seed` is only used on a cold counter. */
  mintReference(year: number, seed: number): Promise<string>;
  /** False when this is the in-process stand-in and not the real thing. */
  readonly arbitrates: boolean;
}

// ---------------------------------------------------------------------------
// The real one
// ---------------------------------------------------------------------------

class DurableObjectCoordination implements CaseCoordination {
  readonly arbitrates = true;
  readonly #cases: CloudflareEnv["CASE_COORDINATOR"];
  readonly #minter: CloudflareEnv["REFERENCE_MINTER"];
  /** The mirror those objects write. Absent is a degraded read, not a crash. */
  readonly #db: D1Database | undefined;

  constructor(
    cases: CloudflareEnv["CASE_COORDINATOR"],
    minter: CloudflareEnv["REFERENCE_MINTER"],
    db: D1Database | undefined,
  ) {
    this.#cases = cases;
    this.#minter = minter;
    this.#db = db;
  }

  /**
   * `idFromName(caseId)` — exactly as CLAUDE.md specifies.
   *
   * Written out rather than using `getByName` so the addressing scheme is
   * legible at the call site: the case id IS the object's name, which is why
   * two reviewers on the same case reach the same instance and two reviewers
   * on different cases never contend.
   */
  #forCase(caseId: string) {
    return this.#cases.get(this.#cases.idFromName(caseId));
  }

  state(caseId: string): Promise<CoordinatorState> {
    return this.#forCase(caseId).state(caseId, new Date().toISOString());
  }

  /**
   * One query, not sixteen round trips.
   *
   * Read from the `claims` table rather than by fanning out across every
   * case's object, which is the shape this would otherwise take and which
   * grows with the queue. The objects write that table inside the same turn
   * they grant or release, so it lags only a failed write — and a stale mirror
   * costs a wrong row on a list, never a wrong arbitration, because the write
   * is refused at the object regardless of what this says.
   *
   * Every row is read and `claimIsLive` decides, rather than filtering with a
   * SQL comparison. ISO-8601 would compare correctly, so this is not about
   * whether it works: `WHERE expires_at > ?` is a SECOND liveness rule, and
   * the day the first one changes — a grace period, a different clock — it is
   * the copy nobody edits. The table is bounded by cases-ever-claimed, so
   * there is nothing to win by filtering in SQL anyway.
   *
   * Reading them all is also what makes the fixture holders work. A row exists
   * iff an object has spoken about that case, so a lapsed or released row is
   * exactly what must suppress the seed — excluding it in SQL would hand case
   * 105 back to A. Okonkwo the moment somebody released it. Same rule as
   * `#liveClaim` inside the object, so the queue and the case screen cannot
   * disagree about who holds what.
   */
  async held(): Promise<ReadonlyMap<string, CaseClaim>> {
    const now = new Date().toISOString();
    const claims = new Map<string, CaseClaim>();
    const spokenFor = new Set<string>();

    if (this.#db !== undefined) {
      try {
        const rows = await dbFrom(this.#db).select().from(schema.claims);
        for (const row of rows) {
          spokenFor.add(row.caseId);
          const parsed = StoredCaseClaim.safeParse(row);
          if (parsed.success && claimIsLive(parsed.data, now as IsoDateTime)) {
            claims.set(row.caseId, parsed.data);
          }
        }
      } catch {
        // No table yet, or D1 unreachable. The seeds below are still the
        // truthful part of the answer, and a queue that renders without live
        // claims beats a queue that does not render at all.
      }
    }

    for (const caseId of SEEDED_CASE_IDS) {
      if (spokenFor.has(caseId)) continue;
      const seed = seededHolder(caseId, now as IsoDateTime);
      if (seed !== null) claims.set(caseId, seed);
    }

    return claims;
  }

  claim(
    caseId: string,
    reviewerId: string,
    displayName: string,
    idempotencyKey: string | null = null,
  ): Promise<ClaimOutcome> {
    return this.#forCase(caseId).claim(
      caseId,
      reviewerId,
      displayName,
      new Date().toISOString(),
      idempotencyKey,
    );
  }

  release(
    caseId: string,
    reviewerId: string,
    idempotencyKey: string | null = null,
  ): Promise<CoordinatorState> {
    return this.#forCase(caseId).release(
      caseId,
      reviewerId,
      new Date().toISOString(),
      idempotencyKey,
    );
  }

  rule(
    caseId: string,
    ruling: ReviewerRuling,
    idempotencyKey: string | null = null,
  ): Promise<RuleOutcome> {
    return this.#forCase(caseId).rule(
      caseId,
      ruling,
      new Date().toISOString(),
      idempotencyKey,
    );
  }

  armClock(
    caseId: string,
    reference: string,
    dueOn: IsoDate | null,
  ): Promise<void> {
    return this.#forCase(caseId).armClock(caseId, reference, dueOn);
  }

  /** One instance for the whole application — that is the point of it. */
  mintReference(year: number, seed: number): Promise<string> {
    const stub = this.#minter.get(this.#minter.idFromName("case-reference"));
    return stub.next(year, seed);
  }
}

// ---------------------------------------------------------------------------
// The stand-in
// ---------------------------------------------------------------------------

/**
 * In-process coordination, for `next dev` and for tests.
 *
 * `arbitrates` is false and the UI says so, because this is the one stand-in
 * in the codebase whose difference from the real thing is invisible in normal
 * use and catastrophic in the case the feature exists for. A Map arbitrates
 * perfectly between two tabs on one developer's laptop and not at all between
 * two reviewers on two machines — and the screen looks identical either way.
 *
 * Named for what it is, like UnprotectedBotGate.
 */
class UnarbitratedCoordination implements CaseCoordination {
  readonly arbitrates = false;
  readonly #claims = new Map<string, CaseClaim>();
  readonly #rulings = new Map<string, ReviewerRuling>();
  readonly #counters = new Map<number, number>();
  /**
   * Replayed results, so a double-submit behaves the same here as on the real
   * object.
   *
   * Worth having even though this stand-in arbitrates nothing: if `next dev`
   * accepted a double-click that production collapses, the behaviour a
   * developer tests is not the behaviour that ships, and this is exactly the
   * kind of difference that is invisible until it is a duplicated ruling in a
   * regulatory log. No TTL — the map dies with the isolate, which is sooner
   * than any TTL would fire.
   */
  readonly #replays = new Map<string, unknown>();

  async #once<T>(key: string | null, work: () => Promise<T>): Promise<T> {
    if (key === null || key === "") return work();
    if (this.#replays.has(key)) return this.#replays.get(key) as T;
    const result = await work();
    this.#replays.set(key, result);
    return result;
  }

  /**
   * Same rule as the Durable Object's `#liveClaim`, for the same reason.
   *
   * A stored claim always wins and is expiry-filtered; the fixture holder
   * answers only where nothing is stored. A lapsed entry is KEPT rather than
   * deleted — deleting would return the case to never-spoken and the fixture
   * would spring back, so releasing case 105 would hand it to A. Okonkwo
   * again. The stand-in has to agree with the real object about this, or the
   * demo behaves differently under `next dev` than it does deployed, which is
   * the one thing a stand-in must never do.
   */
  #live(caseId: string, now: string): CaseClaim | null {
    const claim = this.#claims.get(caseId);
    if (claim === undefined) return seededHolder(caseId, now as IsoDateTime);
    return claimIsLive(claim, now) ? claim : null;
  }

  async state(caseId: string): Promise<CoordinatorState> {
    return {
      claim: this.#live(caseId, new Date().toISOString()),
      ruling: this.#rulings.get(caseId) ?? null,
      clock: null,
    };
  }

  /** The Map is the mirror here, and the seeds fold in on the same rule. */
  async held(): Promise<ReadonlyMap<string, CaseClaim>> {
    const now = new Date().toISOString();
    const claims = new Map<string, CaseClaim>();

    for (const [caseId, claim] of this.#claims) {
      if (claimIsLive(claim, now)) claims.set(caseId, claim);
    }

    for (const caseId of SEEDED_CASE_IDS) {
      if (this.#claims.has(caseId)) continue;
      const seed = seededHolder(caseId, now as IsoDateTime);
      if (seed !== null) claims.set(caseId, seed);
    }

    return claims;
  }

  async claim(
    caseId: string,
    reviewerId: string,
    displayName: string,
    idempotencyKey: string | null = null,
  ): Promise<ClaimOutcome> {
    return this.#once(idempotencyKey, async () => {
      const now = new Date().toISOString();
      const existing = this.#live(caseId, now);

      if (existing !== null && existing.reviewerId !== reviewerId) {
        return { kind: "held_by_other", claim: existing };
      }

      const claim: CaseClaim = {
        reviewerId,
        displayName,
        heldSince: existing?.heldSince ?? now,
        expiresAt: claimExpiryFrom(now),
      };

      this.#claims.set(caseId, claim);
      return existing === null
        ? { kind: "granted", claim }
        : { kind: "already_yours", claim };
    });
  }

  async release(
    caseId: string,
    reviewerId: string,
    idempotencyKey: string | null = null,
  ): Promise<CoordinatorState> {
    return this.#once(idempotencyKey, async () => {
      const now = new Date().toISOString();
      const existing = this.#live(caseId, now);
      // Lapsed, not deleted — see `#live`.
      if (existing?.reviewerId === reviewerId) {
        this.#claims.set(caseId, {
          ...existing,
          expiresAt: now as IsoDateTime,
        });
      }
      return this.state(caseId);
    });
  }

  async rule(
    caseId: string,
    ruling: ReviewerRuling,
    idempotencyKey: string | null = null,
  ): Promise<RuleOutcome> {
    return this.#once(idempotencyKey, async () => {
      const existing = this.#live(caseId, new Date().toISOString());
      if (existing === null) {
        return {
          ok: false,
          reason: "Claim this case before ruling on it.",
          state: await this.state(caseId),
        };
      }
      if (existing.reviewerId !== ruling.decidedBy) {
        return {
          ok: false,
          reason: `${existing.displayName} is holding this case.`,
          state: await this.state(caseId),
        };
      }
      this.#rulings.set(caseId, ruling);
      return { ok: true, reason: null, state: await this.state(caseId) };
    });
  }

  async armClock(
    _caseId: string,
    reference: string,
    dueOn: IsoDate | null,
  ): Promise<void> {
    // Standing a clock down is a no-op with nothing to stand down, so it says
    // nothing. The nightly sweep calls this for EVERY open case, most of which
    // want no clock at all, and logging those produced a failure line per case
    // per night — a wall of red about work nobody asked for, which is how a log
    // stops being read.
    if (dueOn === null) return;

    // There is no alarm without a Durable Object, and there is no honest way
    // to fake one — a setTimeout dies with the process and would be a promise
    // to notify that nothing keeps. So a clock that was genuinely WANTED and
    // cannot be armed is still reported, every time.
    audit({
      actor: "system",
      action: "arm_expedited_clock",
      target: reference,
      outcome: "failure",
      detail: { reason: "no_durable_object_bound", dueOn },
    });
  }

  async mintReference(year: number, seed: number): Promise<string> {
    const current = this.#counters.get(year) ?? Math.max(seed, 0);
    const next = current + 1;
    this.#counters.set(year, next);
    return `SN-${year}-${String(500_000 + next).padStart(6, "0")}`;
  }
}

const standIn = new UnarbitratedCoordination();

export async function getCaseCoordination(): Promise<CaseCoordination> {
  const env = await getCloudflareEnv();
  const cases = env?.CASE_COORDINATOR;
  const minter = env?.REFERENCE_MINTER;
  if (cases === undefined || minter === undefined) return standIn;
  // D1 may be absent while the objects are bound. That degrades `held()` to
  // the fixture holders and nothing else; it does not stop anyone claiming.
  return new DurableObjectCoordination(cases, minter, env?.DB);
}

export type { CoordinatorState, RuleOutcome };
