/**
 * The Worker's real entry point.
 *
 * WHY THIS FILE EXISTS AT ALL.
 *
 * `opennextjs-cloudflare build` generates `.open-next/worker.js`, and it
 * regenerates it from scratch on every build. That file exports exactly one
 * thing the platform can use: a `fetch` handler. Everything Clusters D, E and
 * F need is something a Worker declares *alongside* fetch —
 *
 *   D  a Durable Object class, exported by name so the binding can find it
 *   E  a `queue` handler, so a Queues consumer has somewhere to arrive
 *   F  a `scheduled` handler, so a Cron trigger has somewhere to arrive
 *
 * — and none of them can be added to a generated file that is overwritten
 * every time. So `wrangler.jsonc` points `main` at this module instead, and
 * this module imports the generated one and re-exports it unchanged. Next.js
 * still serves every request; it simply no longer owns the entry.
 *
 * The re-exports below are not optional. A Durable Object class that is not
 * exported FROM THE ENTRY MODULE does not exist as far as the runtime is
 * concerned, however correctly it is bound — including OpenNext's own three,
 * which are only reachable through the generated worker and would silently
 * vanish the moment we stopped re-exporting them.
 */

// Generated by `opennextjs-cloudflare build`; shape declared in
// worker/open-next.d.ts, because the file does not exist on a fresh checkout.
// Referenced rather than duplicated so that whatever OpenNext decides its
// handler should do stays OpenNext's business.
import openNextWorker from "../.open-next/worker.js";

/**
 * OpenNext's own Durable Objects, passed straight through.
 *
 * These back Next's incremental cache, its tag cache and its cache purging.
 * We bind none of them today (see open-next.config.ts — that is Cluster D's
 * *optional* half and deliberately still on defaults), but the export costs
 * nothing and its absence would be a confusing runtime error the day one is
 * switched on.
 */
export {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from "../.open-next/worker.js";

/** Cluster D. One case, one reviewer, arbitrated in one place. */
export { CaseCoordinator } from "../src/lib/coordinator/case-coordinator";

/**
 * Cluster D. One place where the public case reference is incremented.
 *
 * A separate class rather than a well-known instance of CaseCoordinator: they
 * have opposite addressing. CaseCoordinator wants one instance PER CASE so
 * that reviewers on different cases never contend; the minter wants exactly
 * ONE instance for the whole application, because a counter that shards is not
 * a counter.
 */
export { ReferenceMinter } from "../src/lib/coordinator/reference-minter";

interface WorkerHandler {
  fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<Response>;
}

const nextHandler = openNextWorker as WorkerHandler;

/**
 * Named rather than exported anonymously, so a stack trace and the lint rule
 * both have something to call it.
 */
const sidenoteWorker = {
  /** Every HTTP request. Unchanged — this is Next.js, via OpenNext. */
  fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<Response> {
    return nextHandler.fetch(request, env, ctx);
  },

  // Cluster E adds `queue` here, and Cluster F adds `scheduled`. Both are
  // sibling handlers on this same object; neither exists yet, and a stub that
  // accepted a cron tick and did nothing would be worse than no handler at
  // all — Cloudflare reports a missing handler, and reports a silent one as a
  // successful run.
};

export default sidenoteWorker;
